// AUTO-GENERATED from Moien app section_1.json — do not edit by hand.
// Run the generator in the Moien session to refresh.

export type MoienUnit = { id: string; titleLb: string; items: string[] };

export const MOIEN_SECTION = "A1.1";
export const MOIEN_TOTAL_ITEMS = 885;

export const MOIEN_UNITS: MoienUnit[] = [
  {
    "id": "s1-u01",
    "titleLb": "Moien!",
    "items": [
      "Moien",
      "Äddi",
      "Merci",
      "Jo",
      "merci",
      "schlecht",
      "Schlecht",
      "Bonjour",
      "Nee",
      "nee",
      "Gutt",
      "Moien, wéi geet et?",
      "Gutt, merci",
      "Wéi geet et?",
      "Wéi heescht du?",
      "Wou wunns du?",
      "Wéi al bass du?",
      "Wéi geet et ?",
      "Et geet gutt, merci",
      "Bis muer",
      "bis muer",
      "Äddi, bis muer!",
      "Wann ech gelift",
      "Jo, wann ech gelift",
      "Moien , wéi geet et ?",
      "Äddi , merci !",
      "Moien! Wéi geet et? Gutt, merci!",
      "Merci villmools",
      "merci villmools",
      "Gutt , merci , an dir ?",
      "Merci villmools, Äddi!"
    ]
  },
  {
    "id": "s1-u02",
    "titleLb": "Ech sinn …",
    "items": [
      "Lëtzebuerg",
      "Däitschland",
      "Frankräich",
      "Italien",
      "Ech heeschen Anna",
      "Ech sinn Anna",
      "Anna kënnt",
      "Moien Anna",
      "Ech heeschen",
      "Ech sinn",
      "Ech kommen",
      "Ech wunnen",
      "Wéi heescht du?",
      "Ech heeschen Tom",
      "Moien, ech heeschen Anna",
      "Ech sinn den Tom",
      "Tom kënnt",
      "Moien Tom",
      "Tom ësst",
      "Ech sinn d'Anna",
      "Ech sinn den Anna",
      "Ech heeschen Anna net",
      "Ech ginn",
      "Du bass",
      "Ech sinn den Tom an du bass d'Anna",
      "Hien ass",
      "Si ass d'Anna",
      "Hien ass d'Anna",
      "Si ass den Anna",
      "Si heescht Tom",
      "Si ass",
      "Hien ass den Tom an si ass d'Anna",
      "Si heescht Anna",
      "Ech kommen aus Däitschland",
      "Ech kommen aus Frankräich",
      "Ech wunnen zu Paräis",
      "Ech sinn Frankräich",
      "Ech kommen aus Portugal",
      "Ech kommen aus Italien",
      "Wou wunns du?",
      "Ech wunnen zu Lëtzebuerg",
      "Ech kommen aus Lëtzebuerg",
      "Ech sinn Lëtzebuerg",
      "Lëtzebuerg ass schéin",
      "Ech wunnen zu",
      "Ech kommen aus",
      "Ech sinn aus",
      "Wou wunns du ?",
      "Ech wunnen zu Lëtzebuerg-Stad",
      "Moien , ech heeschen Tom an ech kommen aus Däitschland",
      "Wéi al bass du?",
      "Wou kënns du hier?",
      "Ech wunnen zu Esch",
      "Moien, ech heeschen Léiwchen an ech kommen aus Lëtzebuerg"
    ]
  },
  {
    "id": "s1-u03",
    "titleLb": "Zuelen 0–20",
    "items": [
      "null",
      "0",
      "1",
      "5",
      "10",
      "dräi",
      "3",
      "2",
      "4",
      "fënnef",
      "6",
      "zwee",
      "Zwee",
      "siwen",
      "7",
      "8",
      "9",
      "aacht",
      "néng",
      "zéng",
      "Zéng",
      "eelef",
      "11",
      "12",
      "13",
      "14",
      "zwielef",
      "20",
      "dräizéng",
      "30",
      "33",
      "fofzéng",
      "Fofzéng",
      "siechzéng",
      "16",
      "60",
      "26",
      "uechtzéng",
      "18",
      "80",
      "28",
      "zwanzeg",
      "22",
      "nonzéng",
      "Nonzéng",
      "een, zwee, dräi, véier, fënnef",
      "sechs siwen aacht néng zéng",
      "sechs, siwen, aacht, néng, zéng",
      "eelef, zwielef, dräizéng, véierzéng, fofzéng",
      "siwwenzéng uechtzéng nonzéng zwanzeg",
      "siechzéng, siwwenzéng, uechtzéng, nonzéng, zwanzeg",
      "Wéi al bass du?",
      "Ech sinn zwanzeg Joer al",
      "Ech hunn zwanzeg",
      "Ech kommen aus zwanzeg",
      "Ech wunnen zu zwanzeg",
      "Ech sinn zéng Joer al",
      "Ech sinn dräi Joer al",
      "Ech sinn fofzéng Joer al",
      "Ech sinn aacht Joer al",
      "Wéi al bass du ?",
      "Ech sinn fënnefanzwanzeg Joer al"
    ]
  },
  {
    "id": "s1-u04",
    "titleLb": "D'Famill",
    "items": [
      "d'Mamm",
      "Papp",
      "papp",
      "d'Schwëster",
      "Schwëster",
      "d'Boma",
      "d'Tatta",
      "d'Kand",
      "d'Fra",
      "d'Famill",
      "de Papp",
      "de Brudder",
      "meng Mamm",
      "mäi Mamm",
      "mäin Mamm",
      "mäin Papp",
      "D'Mamm an de Papp",
      "meng Schwëster",
      "mäi Brudder",
      "mäin Brudder",
      "Ech hunn eng Schwëster",
      "de Bopa",
      "meng Boma",
      "Mäi Bopa an meng Boma sinn al",
      "den Onkel",
      "Mäin Onkel an meng Tatta",
      "D'Kand spillt mat der Mamm",
      "de Mann",
      "Meng Fra heescht Anna",
      "Mäi Fra heescht Anna",
      "Mäin Fra ass Anna",
      "Meng Mann ass Anna",
      "Mäi Mann heescht Tom",
      "meng Brudder",
      "mäi Schwëster",
      "mäin Onkel",
      "mäi Onkel",
      "meng Onkel",
      "mäin Tatta",
      "meng Tatta",
      "mäi Tatta",
      "meng Famill",
      "Meng Famill ass grouss",
      "Ech hunn e Brudder an eng Schwëster",
      "Ech hu meng Famill gär",
      "Ech hunn meng Famill gär",
      "Meng Famill ass meng Welt"
    ]
  },
  {
    "id": "s1-u05",
    "titleLb": "D'Alphabet",
    "items": [
      "Lëtzebuerg",
      "ABCDE",
      "schreiwen",
      "Schreiwen",
      "Anna",
      "A-N-N-A",
      "A-N-A",
      "A-M-N-A",
      "A-N-N-E",
      "ëmmer",
      "héich",
      "hech",
      "hoich",
      "huech",
      "schéin",
      "spéit",
      "Spéit",
      "Äddi",
      "Eddi",
      "Addi",
      "Iddi",
      "Schreif",
      "Lies",
      "Lauschter",
      "Schwätz",
      "Buschtaf",
      "L-Ë-T-Z-E-B-U-E-R-G",
      "A B C D E",
      "E D C B A",
      "A E I O U",
      "B D F H J",
      "A, B, C, D, E, F, G",
      "X Y Z",
      "A B C",
      "T U V",
      "M N O",
      "Wéi schreift een dat?",
      "Wéi heescht du?",
      "Wou wunns du?",
      "Wéi geet et?",
      "Mäin Numm: T-O-M",
      "Lëtzebuerg ass schéin",
      "Mäin Numm ass Anna",
      "Ech sinn Numm",
      "Numm Anna",
      "Mäin Anna",
      "Wéi schreift een Lëtzebuerg ?",
      "de Buschtaf"
    ]
  },
  {
    "id": "s1-u06",
    "titleLb": "Faarwen",
    "items": [
      "rout",
      "blo",
      "gréng",
      "giel",
      "Giel",
      "wäiss",
      "schwaarz",
      "gro",
      "bro",
      "Wäiss",
      "rosa",
      "violett",
      "orange",
      "Gro",
      "Rout, blo, gréng",
      "Schwaarz a wäiss",
      "Mäi Pull ass orange",
      "de Fändel",
      "De Fändel ass rout , wäiss an blo",
      "rout, wäiss, blo",
      "gréng, giel, schwaarz",
      "rosa, violett, orange",
      "wäiss, blo, gréng",
      "De Lëtzebuerger Fändel",
      "De Lëtzebuerger Fändel ass rout, wäiss a blo",
      "Mäin Auto ass rout",
      "Mäin Auto ass blo",
      "Mäin Auto ass gréng",
      "Mäin Auto ass schwaarz",
      "rout, blo, gréng",
      "Wéi eng Faarw hues du gär ?",
      "Ech hu blo gär"
    ]
  },
  {
    "id": "s1-u07",
    "titleLb": "Doheem",
    "items": [
      "d'Haus",
      "d'Wunneng",
      "d'Zëmmer",
      "d'Schoul",
      "d'Kichen",
      "d'Buedzëmmer",
      "d'Wunnzëmmer",
      "d'Schloofzëmmer",
      "Schloofzëmmer",
      "d'Dësch",
      "doheem",
      "draussen",
      "weider",
      "hei",
      "Mäin Haus ass grouss",
      "D'Kichen ass nei",
      "Mäi Schloofzëmmer ass kleng",
      "den Dësch",
      "de Stull",
      "de Bett",
      "de Frigo",
      "Den Dësch an de Stull",
      "dat Dësch",
      "de Dësch",
      "den Kichen",
      "de Kichen",
      "dat Kichen",
      "dat Kand",
      "dat Bett",
      "Den Dësch, d'Kichen, dat Kand",
      "Mäin Haus huet eng Kichen an e Wunnzëmmer",
      "Ech sinn doheem",
      "Ech sinn doheem an der Kichen"
    ]
  },
  {
    "id": "s1-u08",
    "titleLb": "Hunn",
    "items": [
      "d'Hond",
      "d'Kaz",
      "Hond",
      "Kaz",
      "Vugel",
      "Bopa",
      "Ech hunn",
      "Ech hunn en Auto",
      "Ech sinn en Auto",
      "Ech gi mat dem Auto",
      "Ech hunn keen Auto",
      "Ech sinn",
      "Ech ginn",
      "Ech kommen",
      "Ech hunn en Hond",
      "Ech hunn eng Kaz",
      "Du hues",
      "Hien huet e Vugel",
      "Hien ass e Vugel",
      "Si huet e Vugel",
      "Mir hunn e Vugel",
      "Si huet",
      "Hien huet",
      "Mir hunn",
      "Si huet eng Kaz",
      "Du hues e Brudder",
      "Dir hutt en Hond",
      "Mir hunn en Hond",
      "Si hunn en Hond",
      "Du hues en Hond",
      "Si hunn",
      "Dir hutt",
      "Mir hunn eng Famill",
      "Si hunn zwee Kanner",
      "Mir hunn eng schéin Wunneng",
      "en Hond",
      "eng Hond",
      "den Hond",
      "eng Kaz",
      "en Kaz",
      "de Kaz",
      "e Vugel",
      "en Auto",
      "Ech hunn en Hond an eng Kaz",
      "Hues du en Hond ?",
      "Mäin Hond heescht Rex",
      "Mir hunn dräi Kanner",
      "Mir sinn dräi Kanner",
      "Mir hunn zwee Kanner",
      "Si hunn dräi Kanner",
      "Ech hunn keng Zäit",
      "Ech hunn Zäit",
      "Du hues Zäit",
      "Mir hunn Zäit",
      "Hues du Zäit?",
      "Hues du Zäit",
      "Ech hunn e Brudder an eng Schwëster",
      "Ech hunn eng kleng Famill"
    ]
  },
  {
    "id": "s1-u09",
    "titleLb": "Iessen & Drénken",
    "items": [
      "d'Brout",
      "d'Botter",
      "d'Ee",
      "d'Mëllech",
      "d'Waasser",
      "d'Banann",
      "d'Beier",
      "iessen",
      "drénken",
      "kachen",
      "schaffen",
      "gär",
      "léiwer",
      "vill",
      "d'Fréistéck",
      "Fréistéck",
      "Mëttegiessen",
      "Owesiessen",
      "Snack",
      "Honger",
      "de Kéis",
      "Brout mat Botter a Kéis",
      "de Kaffi",
      "den Tee",
      "Ech drénken Kaffi mat Mëllech",
      "den Apel",
      "Ech iessen en Apel an eng Banann",
      "Ech iessen Brout",
      "Ech drénken Brout",
      "Ech kaafen Brout",
      "Ech hunn Brout",
      "Ech drénken Waasser",
      "Ech iessen a drénken doheem",
      "Ech iessen gär Kéis",
      "Ech drénken gär Kéis",
      "Ech hunn keen Kéis",
      "Ech kaafen Kéis",
      "net gär",
      "Ech drénken gär Tee",
      "Ech iessen gär Brout mat Kéis",
      "Zum Fréistéck iessen ech Brout",
      "Zum Fréistéck iessen ech Brout mat Botter",
      "Ech hätt gär e Waasser",
      "Ech hunn e Waasser",
      "Ech kaafen e Waasser",
      "Ech sinn Waasser",
      "Ech hunn Honger",
      "Ech hunn Duuscht",
      "Ech hunn keng Loscht",
      "Ech hunn Zäit",
      "Ech hunn Honger an Duuscht"
    ]
  },
  {
    "id": "s1-u10",
    "titleLb": "Am Café",
    "items": [
      "d'Kuch",
      "d'Brout",
      "d'Rechnung",
      "d'Käertchen",
      "Prost",
      "Gesondheet",
      "Moien",
      "Äddi",
      "Prost!",
      "d'Mëllech",
      "Ech hätt gär",
      "Ech hätt gär e Kaffi",
      "Ech hunn e Kaffi",
      "Ech sinn e Kaffi",
      "Ech gi mat Kaffi",
      "Ech hunn",
      "Ech wëll",
      "Ech ginn",
      "Ech hätt gär en Tee",
      "Ech hätt gär e Kaffi, wann ech gelift",
      "de Croissant",
      "den Tarte",
      "eng Kuch",
      "E Croissant a Kaffi, wann ech gelift",
      "Wéi vill kascht dat?",
      "Dat kascht zwee Euro",
      "Dat ass zwee Euro",
      "Ech hunn zwee Euro",
      "Zwee Euro Kaffi",
      "fënnef Euro",
      "véier Euro",
      "sechs Euro",
      "dräi Euro",
      "Wéi vill kascht de Kaffi?",
      "Wéi vill kascht de Kaffi",
      "Wéi vill kascht den Tarte?",
      "Ech wëll bezuelen",
      "Ech hunn bezuelt",
      "Ech kafe",
      "Ech hunn keng Sue",
      "den Zocker",
      "de Tarte",
      "D'Rechnung, wann ech gelift",
      "d'Rechnung wann ech gelift",
      "Prost! Op d'Lëtzebuerger Beier!",
      "Ech hätt gär e Kaffi an e Croissant",
      "Mat Zocker, wann ech gelift",
      "Ouni Zocker",
      "Mat Mëllech",
      "Mat Beier",
      "de Kaffi",
      "den Tee",
      "Merci, dat war gutt",
      "Merci dat war gutt",
      "Merci, dat war gutt. Äddi!"
    ]
  },
  {
    "id": "s1-u11",
    "titleLb": "Wochendeeg",
    "items": [
      "Méindeg",
      "Mëttwoch",
      "Dënschdeg",
      "Sonndeg",
      "Donneschdeg",
      "Freideg",
      "Samschdeg",
      "haut",
      "muer",
      "gëschter",
      "elo",
      "Muer",
      "d'Woch",
      "d'Joer",
      "Méindeg, Dënschdeg, Mëttwoch",
      "Haut ass Freideg",
      "Samschdeg a Sonndeg ass Weekend",
      "Sonndeg sinn ech doheem",
      "Haut ass Méindeg, muer ass Dënschdeg",
      "Wéi en Dag ass haut?",
      "Haut ass Donneschdeg",
      "den Dag",
      "de Mount",
      "Méindes schaffen ech"
    ]
  },
  {
    "id": "s1-u12",
    "titleLb": "Méint & Joreszäiten",
    "items": [
      "Januar",
      "Mäerz",
      "Mee",
      "Februar",
      "Abrëll",
      "Juni",
      "Juli",
      "Oktober",
      "Dezember",
      "November",
      "September",
      "August",
      "Fréijoer",
      "Summer",
      "Hierscht",
      "Wanter",
      "Wéini?",
      "Anniversaire",
      "Famill",
      "Joer",
      "Auer",
      "Januar, Februar, Mäerz",
      "Abrëll, Mee, Juni",
      "Juli, August, September, Oktober, November, Dezember",
      "de Summer",
      "de Hierscht",
      "Fréijoer, Summer, Hierscht, Wanter",
      "Mäin Anniversaire ass am Mee",
      "Ech hunn am Mee",
      "Mee ass Mäin",
      "Am Mee ass Méindeg",
      "am Januar",
      "Wéini ass däin Anniversaire ?",
      "Mäin Anniversaire ass am August"
    ]
  },
  {
    "id": "s1-u13",
    "titleLb": "Auer & Zäit",
    "items": [
      "d'Auer",
      "d'Minutt",
      "d'Sekonn",
      "d'Joer",
      "Mëtteg",
      "Mëtternuecht",
      "spéit",
      "Wéivill Auer ass et?",
      "Et ass dräi Auer",
      "Et ass fënnef Auer",
      "Et ass eelef Auer",
      "Et ass aacht Auer",
      "aacht Auer",
      "néng Auer",
      "siwen Auer",
      "zéng Auer",
      "Et ass zéng Auer",
      "Et ass siwen Auer",
      "halwer fënnef",
      "véier op",
      "véier op fënnef",
      "véier vir fënnef",
      "fënnef Auer",
      "véier vir dräi",
      "Et ass halwer zéng",
      "den Owend",
      "de Moien",
      "Et ass Mëtteg",
      "um aacht Auer",
      "Um wéivill Auer fänks du u schaffen ?",
      "um néng Auer",
      "um zéng Auer",
      "um siwen Auer",
      "Ech schaffen um aacht Auer",
      "Mir treffen eis um siwen Auer",
      "Mir sinn um siwen",
      "Um siwen ass Mëtteg",
      "Siwen Auer schaffen mir",
      "halwer eelef",
      "halwer zéng",
      "halwer zwielef",
      "halwer néng",
      "Et ass halwer néng",
      "Et ass spéit, ech muss goen"
    ]
  },
  {
    "id": "s1-u14",
    "titleLb": "Net / Keen",
    "items": [
      "net",
      "keen",
      "nee",
      "näischt",
      "nimools",
      "neminere",
      "ëmmer",
      "Ech sinn net miid",
      "Ech sinn miid",
      "Ech hunn net miid",
      "Ech net sinn miid",
      "Ech kommen net",
      "Ech wunnen net zu Paräis",
      "Ech hunn keen Hond",
      "Ech hunn net en Hond",
      "Ech sinn keen Hond",
      "Ech hunn en Hond net",
      "Ech hunn keng Kaz",
      "Ech hunn keen Kaz",
      "Ech sinn keng Kaz",
      "Kaz hunn ech net",
      "keng Zäit",
      "kee Wëssen",
      "kee Plang",
      "net méi",
      "Ech hunn keng Zäit",
      "Ech hunn keen Hond an keng Kaz",
      "Ech weess näischt",
      "Ech rauchen nimools",
      "Neminere ass hei",
      "Neminere kënnt",
      "Hei ass neminere",
      "och net",
      "Ech och net",
      "Ech och",
      "Net ech",
      "Och ech",
      "nach net",
      "Ech drénken kee Wäin , an du och net",
      "Ech hunn keng Zäit, an hien och net"
    ]
  },
  {
    "id": "s1-u15",
    "titleLb": "Beruffer",
    "items": [
      "d'Hausfra",
      "d'Aarbecht",
      "Beruff",
      "Aarbecht",
      "Schoul",
      "Sprooch",
      "de Léierin",
      "den Dokter",
      "de Polizist",
      "de Coiffeur",
      "de Beamten",
      "Ech sinn Léierin",
      "Ech si Léierin",
      "Ech sinn Dokter zu Lëtzebuerg",
      "den Etudiant",
      "den Ingenieur",
      "Ech sinn Polizist",
      "Mäi Brudder ass Coiffeur",
      "Ech sinn Etudiant",
      "Si ass Ingenieur an hien ass Etudiant",
      "Meng Mamm ass Hausfra",
      "Wat schaffs du?",
      "Wat schaffs du ?",
      "Wéi heescht du?",
      "Wou wunns du?",
      "Wéi al bass du?",
      "Ech schaffen zu Lëtzebuerg",
      "Ech sinn Léierin a schaffen an enger Schoul",
      "Mäi Papp ass Ingenieur",
      "Mäi Papp huet Ingenieur",
      "Papp Ingenieur ass",
      "Mäi Mamm ass Ingenieur",
      "Ech schaffen als Dokter",
      "de Beruff",
      "Mäi Beruff ass Ingenieur"
    ]
  },
  {
    "id": "s1-u16",
    "titleLb": "Schoul & Léieren",
    "items": [
      "d'Schoul",
      "d'Universitéit",
      "d'Klass",
      "d'Buch",
      "léieren",
      "d'Sprooch",
      "Franséisch",
      "Däitsch",
      "Englesch",
      "Lëtzebuergesch",
      "schwätzen",
      "verstoen",
      "héieren",
      "schreiwen",
      "schaffen",
      "de Cours",
      "D'Schoul ass grouss",
      "de Bic",
      "e Buch",
      "Ech hunn e Buch an e Bic",
      "Ech léieren Lëtzebuergesch",
      "Ech schwätzen Lëtzebuergesch",
      "Ech sinn Lëtzebuergesch",
      "Ech kommen aus Lëtzebuerg",
      "Ech léieren",
      "Ech schaffen",
      "Ech wunnen",
      "Ech kommen",
      "Mir léieren",
      "Ech léieren all Dag Lëtzebuergesch",
      "Ech schwätzen Däitsch, Franséisch an Englesch",
      "Ech verstinn net",
      "Ech weess net",
      "Ech kann net",
      "Ech héieren net",
      "Schwätz du Lëtzebuergesch?",
      "Schwätz du Lëtzebuergesch",
      "Ech verstinn e bësschen Lëtzebuergesch",
      "Ech léieren Lëtzebuergesch an der Schoul",
      "Wat méchs du an der Schoul?",
      "Wou ass d'Schoul?",
      "Wéi vill kascht d'Schoul?",
      "Wéi heescht d'Schoul?",
      "Lëtzebuergesch ass net einfach",
      "Lëtzebuergesch ass schéin, mee net einfach"
    ]
  },
  {
    "id": "s1-u17",
    "titleLb": "Wou? Hei & Do",
    "items": [
      "hei",
      "do",
      "wou",
      "weider",
      "Hei",
      "an",
      "op",
      "ënner",
      "iwwer",
      "virum",
      "hannert",
      "niewend",
      "tëscht",
      "Ech sinn hei, du bass do",
      "D'Buch ass op dem Dësch",
      "D'Buch ass an dem Dësch",
      "D'Buch ass ënner dem Dësch",
      "D'Buch ass iwwer dem Dësch",
      "Mäin Hond ass an der Kichen",
      "D'Kaz ass ënner dem Dësch",
      "D'Kaz ass op dem Dësch",
      "D'Kaz ass an dem Dësch",
      "D'Kaz ass iwwer dem Dësch",
      "D'Lamp ass iwwer dem Dësch",
      "niewend dem Dësch",
      "Den Hond ass hannert dem Stull",
      "Wou ass den Dokter?",
      "Wou ass mäi Buch ?",
      "Wou ass",
      "Wéi ass",
      "Wat ass",
      "Wéini ass",
      "Wou bass du?",
      "Wou bass du",
      "Wou ass d'Schoul, wann ech gelift?",
      "Den Auto ass virum Haus",
      "Den Auto ass hannert dem Haus",
      "Den Auto ass an dem Haus",
      "Den Auto ass op dem Haus",
      "Wou ass den Hond?",
      "Wou ass d'Kaz?",
      "Wou wunns du?",
      "Et ass hei",
      "D'Kaz sëtzt op dem Stull"
    ]
  },
  {
    "id": "s1-u18",
    "titleLb": "Wéieder vum Alldag",
    "items": [
      "goen",
      "kommen",
      "maachen",
      "soen",
      "héieren",
      "gesinn",
      "schaffen",
      "schloofen",
      "spillen",
      "iessen",
      "ëmmer",
      "oft",
      "heiansdo",
      "ni",
      "Ni",
      "haut",
      "muer",
      "Ech ginn heem",
      "Ech kommen heem",
      "Ech sinn heem",
      "Ech wunnen heem",
      "Ech kommen aus Lëtzebuerg",
      "Ech ginn an d'Schoul",
      "Wat méchs du?",
      "Wéi heescht du?",
      "Wéi geet et?",
      "Wou bass du?",
      "Wat méchs du",
      "Wat sees du? Ech verstinn net.",
      "Ech gesinn",
      "Ech héieren",
      "Ech soen",
      "Ech wëll",
      "Ech héieren Musek",
      "Ech gesinn d'Lëtzebuerger Stad",
      "Ech schloofen gutt",
      "Ech schaffen all Dag a schloofen owes",
      "Ech schaffen ëmmer méindes",
      "Ech schaffen all Dag zu Lëtzebuerg",
      "all Dag",
      "all Moien",
      "All Moien drénken ech Kaffi",
      "Ech ginn oft an d'Kino",
      "Ech sinn oft am Kino",
      "Ech kommen oft vum Kino",
      "Kino ech ginn",
      "Ech maachen",
      "Ech ginn",
      "Ech kommen",
      "Mir ginn op d'Aarbecht",
      "Wat méchs du haut?",
      "Haut maachen ech näischt"
    ]
  },
  {
    "id": "s1-u19",
    "titleLb": "Eng kleng Geschicht",
    "items": [
      "dann",
      "duerno",
      "well",
      "Dann",
      "mee",
      "an",
      "Mee",
      "zum Schluss",
      "Éischt iessen ech, dann schaffen ech, zum Schluss schloofen ech",
      "Ech sinn miid, mee ech schaffen weider",
      "Ech stinn op an drénken Kaffi",
      "Éischt iessen ech , dann ginn ech schaffen",
      "Ech stinn op",
      "Ech schaffen",
      "Ech schloofen",
      "Ech iessen",
      "Ech ginn op d'Aarbecht",
      "Ech ginn schaffen",
      "Um aacht Auer stinn ech op, dann iessen ech Brout",
      "D'Anna ass aus Portugal an si schafft zu Lëtzebuerg",
      "Den Tom kënnt aus Däitschland, well hien Däitsch schwätzt",
      "Den Tom ass Däitsch a kënnt aus Lëtzebuerg",
      "Tom Däitschland kënnt",
      "Tom schwätzt Lëtzebuergesch",
      "Anna schafft",
      "Anna schloofen",
      "Anna iesst",
      "Anna kommt",
      "Si schwätzt Lëtzebuergesch",
      "D'Anna ass meng Frëndin a si wunnt zu Esch",
      "Ech heeschen Tom an ech wunnen zu Lëtzebuerg",
      "Ech schaffen als Léierin an enger Schoul",
      "Ech hu Lëtzebuerg gär, well et schéin ass",
      "Ech hu Lëtzebuerg net gär",
      "Lëtzebuerg ass net schéin",
      "Ech sinn Lëtzebuerg",
      "Meng Geschicht",
      "Mäi Numm",
      "Meng Famill",
      "Mäi Beruff",
      "Moien, ech heeschen Anna, ech kommen aus Italien an ech wunnen zu Lëtzebuerg. Ech léieren Lëtzebuergesch well ech hei schaffen."
    ]
  },
  {
    "id": "s1-u20",
    "titleLb": "Sektioun-Test A1.1",
    "items": [
      "Äddi",
      "Äddi!",
      "fofzéng",
      "zwanzeg",
      "zwielef",
      "zwee",
      "siwwenzéng",
      "Moien, wéi geet et?",
      "Äddi, wéi heescht du?",
      "Wou wunns du?",
      "Wéi al bass du?",
      "Ech heeschen Tom a kommen aus Däitschland",
      "Tom kommt aus Däitschland",
      "Däitschland Tom heescht",
      "Ech sinn Däitschland",
      "Wéi heescht du?",
      "Wéi geet et?",
      "Ech wunnen zu Lëtzebuerg",
      "Moien, ech heeschen … an ech kommen aus …",
      "meng Schwëster",
      "rout, wäiss a blo",
      "gréng, giel, schwaarz",
      "rosa, violett, gro",
      "wäiss, blo, gréng",
      "Ech sinn uechtzéng Joer al",
      "Meng Famill: de Papp, d'Mamm, de Brudder an d'Schwëster",
      "Ech hätt gär e Kaffi, wann ech gelift",
      "Ech hunn e Kaffi",
      "Kaffi ech wëll",
      "Ech sinn Kaffi",
      "Et ass halwer zéng",
      "Ech sinn Léierin",
      "Ech hunn Léierin",
      "Léierin ech ass",
      "Mäi Léierin",
      "Ech hunn Honger",
      "Ech hunn Duuscht",
      "Ech hunn Zäit",
      "Ech hunn keng Loscht",
      "Wéi vill kascht dat?",
      "Wéi vill kascht dat",
      "Um aacht Auer iessen ech mat menger Famill",
      "Moien , ech heeschen Anna an ech kommen aus Portugal",
      "Ech wunnen zu Lëtzebuerg a léieren Lëtzebuergesch",
      "Ech hunn e Brudder an eng Schwëster",
      "Ech sinn e Brudder",
      "Mäi Brudder ass meng Schwëster",
      "Brudder ech hunn",
      "Lëtzebuerg ass schéin",
      "Lëtzebuerg ass grouss",
      "Lëtzebuerg ass kleng",
      "Lëtzebuerg ass kal",
      "Ech hu Lëtzebuerg gär",
      "Ech hunn Lëtzebuerg gär",
      "Moien! Ech heeschen Léiwchen an ech sinn frou, datt du Lëtzebuergesch léiers!"
    ]
  }
];
